project:
  type: website
  output-dir: docs

website:
  title: "easydata"
  navbar:
    search: true
    right:
      - about.qmd
      - icon: github
        href: https://github.com/kurt1984
format:
  html:
    theme: cosmo
    css: styles.css







